kom-senapati/bot-verse

CODE_OF_CONDUCT.md

Fixes #6 Added Code Of Conduct

Fixes #6 #Added CODE_OF_CONDUCT.md

---

app.py

This pull request refactors the app.py file to enhance the configuration and security of the Flask application. The following changes have been made:
- Updated database URI to use environment variables for better security and flexibility.
- Set the secret key to be retrieved from environment variables, providing a safer default mechanism.
- Organized the import statements for clarity.
- Ensured adherence to best practices in Flask application structure.
- These modifications aim to make the application more maintainable and secure for production environments.

Refactor app.py for Improved Configuration and Security

---

routes.py
templates/login.html
templates/signup.html

This PR fixes: #10 
- Adds error messages on authentication pages (siginup/login).

fix #10: Authentication error management

---

templates/base.html
templates/index.html

- new landing page design
- viewport fix for mobile screens

landing page and viewport fix

---

routes.py
templates/profile.html
templates/profile_edit.html

- fixes #20 
- implemented profile name and username edit
- Demo
https://github.com/user-attachments/assets/c73ccaaa-6fd4-432f-9f9a-f61e16159d04

fix #20: profile name and username edit

---

README.md
app.py
templates/base.html
templates/chatbot_hub.html
templates/dashboard.html
templates/profile.html

Added Search Functionality to Filter Chatbots in Dashboard

---

templates/chatbot.html

fixes: #25 
- added Text-to-speech
- added Speech-to-text
Demo
https://github.com/user-attachments/assets/155c6c32-9f64-458e-a554-2c54c2a402b7

feat: Speech Recognition and Synthes

---

templates/chatbot.html
templates/profile.html

fixes #33 
- uses local storage to store

feat: Speech voice change settings

---

templates/profile.html
templates/update_chatbot.html

Transformed update_chatbot.html into a Stunning, Interactive User Experience

---

templates/create_chatbot.html
templates/profile.html

Transformed create_chatbot.html into a Stunning, Interactive User Experience

---

templates/chatbot_hub.html
templates/dashboard.html
templates/profile.html

Enhanced Navbar and Add Logout Icon

---

README.md
templates/base.html
templates/chatbot_hub.html
templates/dashboard.html
templates/profile.html

Added Dark and Light Mode Toggle with Visual Enhancements 

---

README.md

This pull request addresses inaccuracies in the installation guide for the **Bot Verse**. The previous documentation contained misleading information that could confuse users during the setup process.
- **Updated Installation Steps**: Clarified and corrected the installation procedure to ensure users can set up the repository without issues.
- **Corrected Command Examples**: Fixed examples of commands that were outdated or incorrect, aligning them with the current repository structure.
Accurate documentation is vital for fostering a positive experience for users and contributors. The previous guide could lead to frustration and hinder onboarding for new users. This update aims to create a more intuitive and user-friendly installation process.
- Fixes #42 
The updated installation steps …

Fix: Correct installation guide for bot-verse

---

routes.py
templates/dashboard.html

We have added **6 new chatbots** to the system for an enriched user experience!
- **6 New Chatbots**: Explore a fresh set of chatbots with enhanced functionality.
- **View More/View Less Feature**: 
- Initially, only the first 3 chatbots are shown.
- You can now click **View More** to see additional chatbots.
- After expanding, you can also collapse the view by using the **View Less** button for a cleaner interface.
1. **Search**: Use the search bar to filter through the chatbots by name or description.
2. **View More**: Initially, only 3 chatbots are visible. Click the **View More** button to see the rest.
3. **View Less**: After expanding, click the **View Less** button to return to the initial view.

Feat: Add 6 New Chatbots to the Hub with Enhanced View Functionality

---

.github/Issue_templates/BUG_report_issue_template.md
.github/Issue_templates/Feature_request_issue_template.md
.github/Pull_Request_template.md

✅ Fixes issue #19 
This PR includes changes to add new & improved Issue templates & PR template that can be used by new contributors to easily create informative issues & PRs that contain precise info.
* [`.github/Issue_templates/BUG_report_issue_template.md`](diffhunk://#diff-cd1511db3bf5a562cd0cf61f23d23c23fede8b616a4355f838f162db1aff382fR1-R52): Added a comprehensive bug report template to guide users in reporting bugs effectively.
* [`.github/Issue_templates/Feature_request_issue_template.md`](diffhunk://#diff-5c16b96d83a8e5707e875b870541ec55a83ddaf6cd57000b70b8f32dbbcdfa0bR1-R52): Introduced a feature request template to help users suggest enhancements and improvements.
* [`.github/Pull_Request_template.md`](diffhunk://#diff-c710f5ed7890dd18e8c61a036ace3fd59ebf932352fde36aac92b35d70e7 …

Add Issues & PR templates

---

.github/workflows/main.yml
README.md

Fixes: #45
**Automatically Update Contributors List using GitHub Action**
This PR introduces a new GitHub Action that automatically updates the list of contributors in the `README.md`. The action will run on every push to the `main` branch and fetch the latest contributors, displaying their profile images and links to their GitHub profiles. The action helps to keep the contributors list up-to-date without any manual intervention.
Key Features:
- Automatically adds new contributors to the `README.md`.
- Fetches contributor profile images and links them to their respective GitHub profiles.
- Runs on every push to the `main` branch.
For more information or customization options, please refer to the [contributors-readme-action repository](https://github.com/akhilmhdh/contributors-readme-action …

feat: Add Github Action to Automatically update contributors Data

---

README.md

Enhanced readme and fixed all .md links to main readme file

---

ai.py
app.py
models.py
routes.py
run.py

Closes #54 
type annotations for functions and variables for better dev experience.

refactor: added type annotations

---

static/js/dashboard.js
templates/dashboard.html

Closes: #60
Fixed Chatbot Delete and Publish Form
Click on Publish and delete action to created chatbot

fix #60: fixed Publish and Delete form

---

routes.py
static/app.js
static/css/tailwind.css
static/js/landing.js
tailwind.config.js
templates/base.html
templates/chatbot.html
templates/chatbot_hub.html
templates/create_chatbot.html
templates/dashboard.html
templates/index.html
templates/login.html
templates/profile.html
templates/profile_edit.html
templates/signup.html
templates/update_chatbot.html

- Closes: #57
Overall UI update with consistent theme
https://github.com/user-attachments/assets/0885240a-5891-4039-b632-6ddeb5f87e50

Fixes: #57 Redesign whole website and fix broken ui and theme

---

models.py
routes.py
static/js/profile.js
templates/chatbot.html
templates/chatbot_hub.html
templates/dashboard.html
templates/index.html
templates/profile.html
templates/profile_edit.html

- Closes: #53 
- Adds user avatar and bio
- Adds bot avatar

Fixes #53: feature adds user and bot avatars and user bio

---

constants.py
routes.py
static/js/dashboard.js
templates/dashboard.html

Closes: #68 
Adds more chatbots that were accidentally removed in conflict.
All credit goes to @Ayushjhawar8. Sorry My friend

feat: more bots

---

routes.py

H @kom-senapati !! This is with reference to the issue #66 raised by me yesterday. I have made the following changes to the code:-
1.Blueprints: Introduced Flask Blueprints for better route organization.
2.Docstrings: Added docstrings to all route functions.
3.Error Handling: Improved error handling with try-except blocks for database operations.
4.Security: Ensured user inputs are validated and sanitized.
5.Performance: Used eager loading for database queries where applicable.
6.Code Consistency: Ensured consistent use of quotes and formatting throughout the file.
Please check for errors if any. The code required these fixes for proper functioning but overall it was great!! Keep Coding!!
Yash Vashishth
(Contributor, GSSoC'24 and Hacktoberfest)

[perf],[feat] : Changes to routes.py mentioned in issue #66

---

api_routes.py
app.py
constants.py
helpers.py
routes.py
templates/chatbot.html
templates/chatbot_hub.html
templates/create_chatbot.html
templates/dashboard.html
templates/index.html
templates/login.html
templates/profile.html
templates/profile_edit.html
templates/signup.html
templates/update_chatbot.html

Closes: #80
Fixes broken code and refactored code

fixes #80: routing and refactor code

---

static/js/chatbot.js

fixes #75: speaker btn

---

api_routes.py
routes.py
static/app.js
static/js/anonymous.js
templates/anonymous.html
templates/base.html

- Closes: #78 
A anonymous chatting bot which can be used to generate prompt or for temporary chat

fixes #78: Feature a anonymous chat bot 

---

app/routes.py
app/templates/404.html
app/templates/500.html

fix #84: adds 404 and 500 pages

---

app/api_routes.py
app/static/css/styles.css
app/static/css/tailwind.css
app/templates/index.html
tailwind.config.js

the text is now properly aligned on small screens
Fixed: NameError: name 're' is not defined. Did you forget to import 're'
by adding the re library

fix: made the hero text responsive and added the re library

---

app/static/js/login.js
app/static/js/signup.js
app/templates/login.html
app/templates/signup.html

Closes: #106
Implemented an eye icon functionality in the sign-up form's password field to allow users to toggle password visibility.
Tested by manually checking the sign-up form to ensure the eye icon appears and toggles the password visibility correctly.

Feat(App): Add Eye Icon Functionality for Password Field in Sign-Up/ Sign-In Form

---

README.md

I've added the table metrices in readme that will be UPDATED AUTOMATICALLY.
kindly merge it @kom-senapati 
Thank you!
fixes: #118

Added Table metrices in readme

---

.github/workflows/pr-checker.yml

Fixes #121 
**Usage:**
1. When a pull request is created or edited, the workflow automatically triggers.
2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.
**_Note_**: Kindly add all the labels added to the issue, to this PR!

FIX Implement GitHub PR Issue Checker Workflow

---

app/api_routes.py
app/models.py
app/routes.py
app/static/js/imagine.js
app/templates/imagine.html

- Closes: #125 
Saves images in database

feat: save images

---

app/api_routes.py
app/models.py
app/routes.py
app/static/app.js
app/static/js/gallery.js
app/static/js/imagine.js
app/templates/dashboard.html
app/templates/gallery.html
app/templates/imagine.html

- closes: #126 
A image gallery for public images

Feat:  image gallery

---

app/api_routes.py
app/models.py
app/static/js/chatbot_hub.js
app/static/js/gallery.js
app/templates/chatbot_hub.html
app/templates/gallery.html

Closes: #127 
Like and report images

feat: like and report images and bots

---

Darkmode/dark.css
Darkmode/dark.html
Darkmode/dark.js

---
Closes #91
---
---
Implemented a dark/light mode toggle button with a sleek, modern design.
Smooth transitions and responsive styling for an enhanced user experience.
Integrated with local storage to remember user preferences.
---
Dark Mode:
Light Mode:
---

Add Toggle Dark/Light Mode Button with attractive icons

---

app/api_routes.py
app/models.py
client/src/App.tsx
client/src/components/Navbar.tsx
client/src/components/modals/update-profile-modal.tsx
client/src/contexts/auth-context.tsx
client/src/contexts/modals.tsx
client/src/lib/queries.ts
client/src/lib/schemas.ts
client/src/pages/Hub.tsx
client/src/pages/Profile.tsx
client/src/stores/modal-store.ts
client/src/types/types.d.ts

---
Closes #160 
---
- Profile Page
- Update Profile
---
---
---

migration: profile page and updating profile

---

app/api_routes.py
client/src/App.tsx
client/src/components/Navbar.tsx
client/src/lib/queries.ts
client/src/pages/Anonymous.tsx
client/src/pages/Dashboard.tsx
client/src/pages/Imagine.tsx
client/src/pages/Profile.tsx
client/src/pages/UserProfile.tsx

---
- Closes #166
---
- all pages migrated 
- some features migrated
- few tweaks remaining that will be replaced by new solutions in next issues.
---
---
---

migration: imagine and anonymous pages with other features

---

client/src/components/modals/update-profile-modal.tsx
client/src/components/ui/skeleton.tsx
client/src/pages/Chatbot.tsx
client/src/pages/Dashboard.tsx
client/src/pages/Hub.tsx
client/src/pages/Imagine.tsx
client/src/pages/Profile.tsx

---
Closes #179 
---
Loading Skeletions
---
---
---

feat: Loading Skeletons

---

client/src/App.tsx
client/src/components/ChatbotCard.tsx
client/src/components/LikeAndReport.tsx
client/src/components/modals/settings-modal.tsx
client/src/components/theme-toggle.tsx
client/src/contexts/settings-context.tsx
client/src/index.css
client/src/pages/Chatbot.tsx
client/src/pages/Dashboard.tsx
client/tailwind.config.js

---
Closes #150 
---
Multiple Theme support 
- Light
- Dark
- One Dark
- Material Ocean
- Purple Dark
- Discord
---
---
Material Ocean
Purple Dark
Discord 
One Dark
---

feat: Multiple themes

---

app/api_routes.py
client/src/components/BotsLoading.tsx
client/src/components/ChatbotCard.tsx
client/src/components/Navbar.tsx
client/src/lib/queries.ts
client/src/lib/utils.ts
client/src/pages/Dashboard.tsx
client/src/pages/Hub.tsx
client/src/pages/Profile.tsx

---
Closes #5 
---
fix some points:
- Remove and secure `API` routes
- Optimize data fetching and improve static data.
- Code refactor.
---
---
---

fixes: API and bugs in data fetching

---

app/ai.py
app/api_routes.py
client/src/components/modals/settings-modal.tsx
client/src/contexts/settings-context.tsx
client/src/pages/Anonymous.tsx
client/src/pages/Chatbot.tsx

---
Closes #194 
---
Settings to add own API key
---
---
---

feat: User specific API key adding option

---

app/api_routes.py
app/data_fetcher.py
app/models.py
client/src/App.tsx
client/src/components/Navbar.tsx
client/src/lib/queries.ts
client/src/pages/Dashboard.tsx
client/src/pages/Leaderboard.tsx
client/src/types/types.d.ts

---
Closes #193 
---
Leaderboard Page
---
---
---

feat: Leaderboard on basis of contribution score

---

DEVELOPMENT.md
README.md

---
Closes #196 
---
Adds DEVELOPMENT.md
---
---
---

feat: development docs

---

app/ai.py
app/api_routes.py
client/src/components/modals/settings-modal.tsx
client/src/components/ui/input.tsx
client/src/contexts/settings-context.tsx
client/src/pages/Anonymous.tsx
client/src/pages/Chatbot.tsx
client/src/types/types.d.ts
dev-requirements.txt
requirements.txt

---
- Closes #195 
---
Adds Ai engines
- OPENAI
- GROQ
- GEMINI
- ANTHROPIC
---
---
---

feat: Multiple AI engines

---

app/api_routes.py
app/models.py
client/src/lib/queries.ts
client/src/pages/ChatbotView.tsx
client/src/types/types.d.ts

---
Closes #203 
---
Comment Section on chatbot page
---
---
---

feat: Option to Comment on chatbot

---

app/ai.py
app/constants.py
app/data_fetcher.py
app/helpers.py

Solved for Feature: Enhanced Error Handling for API Calls and API Key Validation #201
---
Closes #201
---
API Key Validation: Check that the apiKey variable is not empty before any API requests are made, and raise an error if it is missing.
Error Handling for Network Requests: Add exception handling to catch network errors for all API calls, returning a clear error message in case of a failure.
---
Try for having multiple inputs, and check logs session for checking if the API calls working.
---
---

Enhanced Error Handling for API Calls and API Key Validation #201

---

client/src/components/modals/create-chatbot-modal.tsx
client/src/components/modals/delete-chatbot-modal.tsx
client/src/components/modals/update-chatbot-modal.tsx
client/src/components/modals/update-profile-modal.tsx
client/src/lib/queries.ts
client/src/pages/Anonymous.tsx
client/src/pages/Chatbot.tsx
client/src/pages/ChatbotView.tsx
client/src/pages/Imagine.tsx

---
Closes #209 
---
- Authentication headers error fixed
---
---
---

fixes: authentication headers and 422 error

---

client/src/pages/Chatbot.tsx

---
Closes #213 
---
- settings option on chatting page
- redirect to chatbot view on bot name click
---
---
---

feat: settings option on chatbot page

---

app/ai.py
app/api_routes.py
client/src/components/modals/translate-magic-modal.tsx
client/src/contexts/modals.tsx
client/src/pages/Chatbot.tsx
client/src/stores/modal-store.ts
dev-requirements.txt
requirements.txt

---
Closes #219 
---
Adds Translation Magic Tool
---
---
---

feat: Adds Translation Magic Tool

---

client/package.json
client/src/pages/Chatbot.tsx

Closes #230 
---
- Added emoji picker in chat box of bot
--- Locally
https://github.com/user-attachments/assets/9834d273-89fa-4463-a3ee-29f89b81d7d5
---

Added emoji picker in chat box of bot

---

app/routes.py
app/templates/login.html

---
<span style="color:blue;">&#x2611;</span> Have you renamed the PR title to something meaningful?
---
Closes #145 
---
Added "Remember Me" functionality to the login system, allowing users to stay logged in across sessions by setting a persistent cookie when the option is selected.
---
- Tested the login flow with the "Remember Me" checkbox both checked and unchecked.
- Verified that users remain logged in after closing and reopening the browser when "Remember Me" is selected.
- Confirmed that logging out properly clears the session and any related cookies.
---
---
<span style="color:blue;">&#x2610;</span> Bug fix
<span style="color:blue;">&#x2611;</span> New feature
<span style="color:blue;">&#x2610;</span> Code style update
<span style="color:blue;">&#x2610;</span> Breaking change …

Enhance Login Functionality with "Remember Me" Feature

---

app/api_routes.py
client/src/components/ChatbotCard.tsx
client/src/lib/queries.ts

Closes #229 
---
--- Added delete button on chatbot card & backend query to remove it from db
--- Locally
https://github.com/user-attachments/assets/d8a4926a-83f2-4d8f-b9ad-e1744c300187
---

Added delete button on chatbot card & backend query to remove it from db

---

app/api_routes.py
client/src/App.tsx
client/src/components/ChatbotCard.tsx
client/src/components/ImageCard.tsx
client/src/components/Navbar.tsx
client/src/components/modals/delete-chatbot-modal.tsx
client/src/contexts/settings-context.tsx
client/src/lib/queries.ts
client/src/pages/ChatbotView.tsx
client/src/pages/Hub.tsx
client/src/pages/MyImages.tsx
client/src/pages/Profile.tsx

---
Closes #250 
---
- image managemnt Page and fixes with deleting and publishing
- 
---
---
---

feat: image managemnt Page and fixes with deleting and publishing

---

client/src/App.tsx
client/src/components/ChatbotCard.tsx
client/src/components/Navbar.tsx
client/src/pages/Hub.tsx
client/src/pages/MyChatbots.tsx

---
Closes #255 
---
- Chatbot management Page with bugs fixed
---
---
---

feat: Chatbot management Page with bugs fixed

---

app/api_routes.py

Closes #245 
---
- Pass query string to chatbot
---
Locally
---
---

Pass chatbot latest prompt

---

client/src/pages/MyChatbots.tsx
client/src/pages/MyImages.tsx

---
Closes #256 
---
- Analytics information for chatbot and images
---
---
---

feat: Analytics information for chatbot and images

---

client/package.json
client/src/pages/Chatbot.tsx

Closes #246 
---
Added export button to download conversation as csv
---
local
---
https://github.com/user-attachments/assets/7e67f2b5-757c-47f1-835b-da8c522e8118
---

Added export button to download conversation as csv

---

client/src/pages/Leaderboard.tsx

fix: #227 
Hey @kom-senapati please reviw tehe code and let me know if there are some code chnges to do.

Revamp the leaderborad

---

client/src/pages/Chatbot.tsx

Closes #261 
---
- Clear all chat with single click on button
- local
[](https://github.com/user-attachments/assets/0a77cb97-8119-4148-99e8-ba53a0c3eef3)
- [ \] Bug fix

Clear all chat with single click on button

---

client/src/components/ChatbotCard.tsx
client/src/components/ui/table.tsx
client/src/i18n/locales/en.ts
client/src/pages/Chatbot.tsx
client/src/pages/Dashboard.tsx
client/src/pages/Leaderboard.tsx

---
Closes #269 
---
- UI fixes
- i18n fixes
---
---
---

fixes: UI bugs and translation in some places

---

dev-requirements.txt
requirements.txt

---
Closes #<issue number>
#277
---
---
---
---

Add Missing Modules

---

client/src/pages/Chatbot.tsx

---
Closes #283 
---
- new UI
---
---
---

tweak: Chatbot Chatting page UI revamp

---

client/src/App.tsx
client/src/components/Footer.tsx
client/src/components/Navbar.tsx
client/src/pages/Privacy.tsx
client/src/pages/Signup.tsx
client/src/pages/Terms.tsx

---
Closes #290 
---
- terms and privacy pages
---
---
---

feat: Terms and Privacy Pages

---

client/src/App.tsx
client/src/lib/custom-switch.tsx
client/src/pages/About.tsx

---
Closes #292 
---
- about and contributors wall
---
---
---

feat: Adds About and Contributors Wall

---

.github/workflows/pr_merge.yml
.github/workflows/pr_raise.yml

---
Closes #224 
---
adds:
- PR Raise message `pr_raise.yaml`
- PR merge message `pr_merge.yaml`
---
---
---

feat: Adds Greeting PR workflows

---

.github/pull_request_template.md
.github/workflows/pr_raise.yml
client/src/lib/schemas.ts
client/src/pages/Signup.tsx

---
Closes #101 
---
added
- confirm Password input
- password hide/show button
---
---
---

feat: Confirm Password and hide button
